/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2016-06-23 06:53:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html><head>\r\n");
      out.write("<title>SBI</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<link href=\"css/sbi_css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script language=\"JavaScript\" src=\"script/sbi.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"loginprocess.do\" method=\"post\">\r\n");
      out.write("<table height=\"70%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tbody><tr> \r\n");
      out.write("    <td class=\"logo\">&nbsp; </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td align=\"center\"><table class=\"login_table\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("        <tbody><tr> \r\n");
      out.write("          <td class=\"login_bar\">Login</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr> \r\n");
      out.write("          <td class=\"login_con\"> <table height=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tbody><tr> \r\n");
      out.write("                <td class=\"login_bg_left\"><img width=\"1\" src=\"../images/dot.gif\"></td>\r\n");
      out.write("                <td class=\"login_bg_right\"><img width=\"1\" src=\"../images/dot.gif\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr> \r\n");
      out.write("                <td class=\"login_left_bg_con\">\r\n");
      out.write("\t\t\t\t\t<table class=\"login_container\" border=\"0\" cellspacing=\"3\" cellpadding=\"0\">\r\n");
      out.write("                    <tbody><tr> \r\n");
      out.write("                      <td>Login ID</td>\r\n");
      out.write("                      <td><input type=\"text\" name=\"username\">\r\n");
      out.write("                      </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr> \r\n");
      out.write("                      <td>&nbsp;</td>\r\n");
      out.write("                      <td>(ex.:dataentry,supervisor,admin)</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr> \r\n");
      out.write("                      <td>Password</td>\r\n");
      out.write("                      <td><input type=\"password\" name=\"password\">\r\n");
      out.write("                      </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td>&nbsp;</td>\r\n");
      out.write("                      <td>(ex.:admin)</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr> \r\n");
      out.write("                      <td>&nbsp;</td>\r\n");
      out.write("                      <td ><input type=\"submit\" value=\"login\"><td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr> \r\n");
      out.write("                      <td>&nbsp;</td>\r\n");
      out.write("                      <td><a class=\"link\" href=\"#\">Forgot Password</a> &nbsp; \r\n");
      out.write("                        <a class=\"link\" href=\"#\">Reset Password</a></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </tbody></table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("                <td class=\"login_bg_right_mid\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td class=\"login_left_bg\"><img width=\"1\" src=\"../images/dot.gif\"></td>\r\n");
      out.write("                <td class=\"login_bg_right_dw\"><img width=\"1\" src=\"../images/dot.gif\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </tbody></table></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </tbody></table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</tbody></table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
